devices:
  samplerate: 44100
  chunksize: 1024
  target_level: 4096
  adjust_period: 3
  resampler:
    type: AsyncSinc
    profile: Balanced
  enable_rate_adjust: true
  capture:
    channels: 2
    device: hw:CARD=UAC2Gadget,DEV=0
    format: S32LE
    type: Alsa
  playback:
    channels: 2
    device: hw:0,0
    format: S32LE
    type: Alsa
