description: null
devices:
  adjust_period: null
  capture:
    channels: 2
    device: hw:Loopback,1,0
    format: S32LE
    labels: null
    link_mute_control: null
    link_volume_control: null
    stop_on_inactive: null
    type: Alsa
  capture_samplerate: null
  chunksize: 1024
  enable_rate_adjust: null
  multithreaded: null
  playback:
    channels: 2
    device: hw:0,0
    format: S32LE
    type: Alsa
  queuelimit: null
  rate_measure_interval: null
  resampler:
    profile: Balanced
    type: AsyncSinc
  samplerate: 44100
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_limit: null
  volume_ramp_time: null
  worker_threads: null
filters: null
mixers: null
pipeline: null
processors: null
title: null
