---
camilla_host: "127.0.0.1"
camilla_port: 1234
bind_address: "0.0.0.0"
port: 5005
ssl_certificate: null
ssl_private_key: null
gui_config_file: null
config_dir: "/home/top/AudioBerry/cdsp/configs"
coeff_dir: "/home/top/AudioBerry/cdsp/coeffs"
default_config: "/home/top/AudioBerry/cdsp/configs/uac2.yml"
statefile_path: "/home/top/AudioBerry/cdsp/configs/uac2.yml"
log_file: "/home/top/AudioBerry/cdsp/camilladsp.log"
on_set_active_config: null
on_get_active_config: null
supported_capture_types: null
supported_playback_types: null
